### ISSUE TITLE
Fetch Reports Update

### ISSUE THREAD

**Issue by apmcguigan** [CS-4820-Library-Project/Libly#181]
- Add a help tip button to the dialogue that appears when choosing a non-calendar-year range right in the top left corner of that box, and the help tip will read: "Reports run for date ranges that represent a normal Jan-Dec calendar year, or Jan-last month for calendar years in progress, will be added to (or updated in) the search database. All other date ranges will be saved in the specified folder but not added to the search database."
-  Add help tip button next to "Report will be saved to:" that says: "See Other Reports Directory setting in Settings for default"  
- Select Report Types help tip - change to: Only reports supported by each respective vendor will be retrieved, and unsupported reports will be listed in "Expand" results

**Comment by zihhuang** [comment]
Finish
