### ISSUE TITLE
Fetch Special Reports Update

### ISSUE THREAD

**Issue by apmcguigan** [CS-4820-Library-Project/Libly#182]
- Help tip at top of attributes/filters box:
Filters will limit your data to just the selected options (implies also showing that attribute).
- Add help tip button at top of Date Range: "many vendors do not support a date range longer than 12 consecutive months"
- Add help tip button next to "Report will be saved to:" that says: "See Other Reports Directory setting in Settings for default"

- The "show" checkboxes will break down your data by displaying extra columns with the selected attributes (usually results in more lines per item)
- You can show the attribute breakdown without filtering to specific values.

**Comment by zihhuang** [comment]
Done: Add help tip button at top of Date Range: "many vendors do not support a date range longer than 12 consecutive months"
Add help tip button next to "Report will be saved to:" that says: "See Other Reports Directory setting in Settings for default"

**Comment by zihhuang** [comment]
I am no idea what are those two mean
The "show" checkboxes will break down your data by displaying extra columns with the selected attributes (usually results in more lines per item)

You can show the attribute breakdown without filtering to specific values
