### ISSUE TITLE
Search Update

### ISSUE THREAD

**Issue by apmcguigan** [CS-4820-Library-Project/Libly#183]
- When user adds "or" line, the word "OR" should appear between the two boxes (either flush left or approximately centered, maybe below the "text input" label) to remind the user of the search logic about to be applied. Ditto for the word "AND" as a label between the AND boxes when another one is added
- Get rid of cost-related fields in field pulldowns as they don't work (and not really needed)

**Comment by CJAcorn** [comment]
Costs related fields can stay, they actually work
